apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::276184324456:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S1WWKKFY1VCK
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-24T14:36:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "921"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ad260cbf-bf47-4ebd-9478-f3eccc2bf055
